name: env_eosc556b
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - discretize=0.10.0
  - empymod=2.3.0
  - ipywidgets=8.0.4
  - jupyter=1.0.0
  - matplotlib=3.7.2
  - numpy=1.25.2
  - pillow=10.1.0
  - pip=23.2.1
  - pymatsolver-base=0.2.0
  - python=3.11.6
  - requests=2.31.0
  - scipy=1.11.1
  - setuptools=68.0.0
  - simpeg=0.20.0

